# Uncomment the next line to define a global platform for your project
  platform :ios, '11.0'

target 'EndGame' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EndGame
  pod 'RevealingSplashView'
  pod 'LBTAComponents'
  pod 'NVActivityIndicatorView'
  pod 'NVActivityIndicatorView/AppExtension'
  pod 'TextFieldEffects'
  
end
